name: 'Deploy process model to stage'

on: 
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  perform-checks:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v5'
      - name: 'Perform checks'
        run: |
          npm i
          npm run test
  deploy-to-dev:
    needs: [perform-checks]
    if: ${{ github.event_name == 'workflow_dispatch' }}
    environment: 'default'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v5'
      - name: 'Deploy to dev'
        run: |
          npm i
          npm run deploy
  deploy-to-test:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v5'
