
name: 'Deploy process model'

on: 
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  perform-checks:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v5'
      - name: 'Perform checks'
        run: |
          npm i
          npm run test
  deploy-to-dev:
    needs: [perform-checks]
    environment: 'default'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v5'
      - name: 'Deploy to dev'
        env:
          ZEEBE_ADDRESS: ${{vars.ZEEBE_ADDRESS}}
          ZEEBE_CLIENT_ID: ${{secrets.ZEEBE_CLIENT_ID}}
          ZEEBE_CLIENT_SECRET: ${{secrets.ZEEBE_CLIENT_SECRET}}
          CAMUNDA_OAUTH_URL: ${{vars.CAMUNDA_OAUTH_URL}}
        run: |
          npm i
          npm run deploy
  deploy-to-test:
    runs-on: 'ubuntu-latest'
    if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
    needs: [perform-checks]
    environment: 'test'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v5'
      - name: 'Deploy to test'
        env:
          ZEEBE_ADDRESS: ${{vars.ZEEBE_ADDRESS}}
          ZEEBE_CLIENT_ID: ${{secrets.ZEEBE_CLIENT_ID}}
          ZEEBE_CLIENT_SECRET: ${{secrets.ZEEBE_CLIENT_SECRET}}
          CAMUNDA_OAUTH_URL: ${{vars.CAMUNDA_OAUTH_URL}}
        run: |
          npm i
          npm run deploy